set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Plugins

Plugin 'vim-syntastic/syntastic'		" syntax highlighting
Plugin 'tpope/vim-fugitive'				" GIT command
Plugin 'tpope/vim-surround'				" command on surround
Plugin 'tpope/vim-repeat'				" Extend repeat command
Plugin 'kien/ctrlp.vim'					" open files with CTRL + P
Plugin 'scrooloose/nerdtree'			" Arborescence de fichiers
Plugin 'scrooloose/nerdcommenter'
Plugin 'majutsushi/tagbar'				" list functions like nerdtree
Plugin 'cohama/lexima.vim'				" autoclose quotes
Plugin 'valloric/youcompleteme'			" autocompletion
Plugin 'vim-airline/vim-airline'		" task bar
Plugin 'vim-airline/vim-airline-themes' " Theme for airline
 
" Plugin Python
" Plugin 'nvie/vim-flake8'				"PEP8

" Plugin Docker
" Plugin 'docker/docker'

" Themes
Plugin 'flazz/vim-colorschemes'			" Themes manager
Plugin 'rakr/vim-one'					" Theme atom-like

call vundle#end()
filetype plugin indent on

set tabstop=4							" 4 spaces for tabulation
set encoding=utf-8
set number 								" activate ligne numbers
set relativenumber
syntax on

source ~/.vim/mappings.vim

" Auto reload file when changed from the outside
set autoread

" Disable swapfiles
set noswapfile

set updatetime=500

" Folding
set foldmethod=indent					" folding by indentation
set foldlevel=1							" folding level when open

" Python highlight
let python_highlight_all=1

colorscheme onedark
let g:airline_powerline_fonts = 1

hi Normal ctermbg=None
