export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="/home/matisla/.oh-my-zsh"

ZSH_THEME="matisla"

export UPDATE_ZSH_DAYS=7

# DISABLE_AUTO_UPDATE="true"
# DISABLE_UPDATE_PROMPT="true"
# DISABLE_MAGIC_FUNCTIONS=true
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# ZSH_CUSTOM=/path/to/new-custom-folder

HIST_STAMPS="dd/mm/yyyy"

plugins=(
	archlinux
	git
	z
	docker
	tmux
	git-prompt
)

source $ZSH/oh-my-zsh.sh

# User configuration

export LANG=fr_FR.UTF-8

# Preferred editor for local and remote sessions

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

if [[ -z $DISPLAY && "$TTY" == '/dev/tty1' ]]; then
	startx
fi

alias vi="nvim"
alias vimdiff="nvim -d"
